name: 'Windows HTTPS Fail'

on:
  workflow_dispatch:

jobs:
  windows-test:
    name: Windows Test
    runs-on: windows-latest
    steps:      
      - name: Install winget
        uses: Cyberboss/install-winget@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install python
        run: winget install python --disable-interactivity --accept-source-agreements --accept-package-agreements
