name: 'Windows Process Priority Fail'

on:
  workflow_dispatch:

jobs:
  windows-test:
    name: Windows Test
    strategy:
      fail-fast: false
      matrix:
        os: [ 'windows-2019', 'windows-2022' ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check Local Process Priority
      shell: powershell
      run: |
        [System.Diagnostics.Process]::GetCurrentProcess().PriorityClass
  linux-test:
    name: Linux Test
    runs-on: ubuntu-latest
    steps:
    - uses: Amadevus/pwsh-script@v2
      id: ps-script
      with:
        script: return [System.Diagnostics.Process]::GetCurrentProcess().PriorityClass.ToString()

    - run: echo '${{ steps.ps-script.outputs.result }}'
